name: example
description: An example app for Expandable package.

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  expandable:
    path: ../

flutter:

  uses-material-design: true

